"""create documents drafts and exports tables

Revision ID: f3ec6e50f5d7
Revises: 08586a33c74d
Create Date: 2026-07-30 17:34:24.789259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ec6e50f5d7'
down_revision: Union[str, Sequence[str], None] = '08586a33c74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('career_session_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_session_id'], ['career_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letter_drafts_career_session_id'), 'cover_letter_drafts', ['career_session_id'], unique=True)
    op.create_table('cv_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('career_session_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_session_id'], ['career_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_drafts_career_session_id'), 'cv_drafts', ['career_session_id'], unique=True)
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('career_session_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_session_id'], ['career_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_career_session_id'), 'exports', ['career_session_id'], unique=False)
    op.create_table('uploaded_cvs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('career_session_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_session_id'], ['career_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_cvs_career_session_id'), 'uploaded_cvs', ['career_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_cvs_career_session_id'), table_name='uploaded_cvs')
    op.drop_table('uploaded_cvs')
    op.drop_index(op.f('ix_exports_career_session_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_cv_drafts_career_session_id'), table_name='cv_drafts')
    op.drop_table('cv_drafts')
    op.drop_index(op.f('ix_cover_letter_drafts_career_session_id'), table_name='cover_letter_drafts')
    op.drop_table('cover_letter_drafts')
    # ### end Alembic commands ###
